version: '3.9'

services:

  # webapp:
  #   container_name: server_webapp
  #   image: node:16.19.0
  #   working_dir: /home/webapp
  #   command: /bin/sh -c "yarn install && yarn db:push && yarn prod"
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - webapp-net
  #   volumes:
  #     - .:/home/webapp
  #   environment:
  #     DATABASE_URL: "mysql://root:password@mysql:3306/webapp"
  #     NODE_ENV: local
  #     PORT: 3000

  mysql:
    image: mysql
    restart: on-failure
    networks:
      - webapp-net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp

  adminer:
    image: adminer
    restart: on-failure
    networks:
      - webapp-net
    ports:
      - 8080:8080

networks:
  webapp-net:
    driver: bridge
